enum GameStatus {
    WAITING_FOR_PLAYERS = 'WAITING_FOR_PLAYERS',
    STARTED = 'STARTED',
    BLACK_CHECKMATE = 'BLACK_CHECKMATE',
    WHITE_CHECKMATE = 'WHITE_CHECKMATE',
    WHITE_WON = 'WHITE WON',
    BLACK_WON = 'BLACK WON'
}

export default GameStatus;